### ISSUE TITLE
Various Fixes / Improvements

### ISSUE THREAD

**Issue by wwoods** [hsadok/pubplot#1]
Hi Hugo,

Thank you again for putting this on GitHub; I appreciate the work and thought you've put into this framework.  I'm working with IEEEtran.cls as well, and can get figures to work perfectly with the following bug fixes / improvements:

- [x] The argument to `pubplot.Document()` is somewhat confusing.  I think I understand why you opted for `documentclass` instead of `document_class`, to mirror LaTeX; but in that case, I would recommend something like `pubplot.Document({'documentclass': '[journal]IEEEtran'})` rather than having two separate fields (so that this option is specified as it would be in the LaTeX document).
- [x] The IEEEtran.cls file includes `\usepackage{times}`, which pubplot does not currently support.  I recommend adding an argument like: `pubplot.Document({'documentclass': '[journal]IEEEtran', 'packages': ['times']})`.  Or, to be more flexible: `pubplot.Document({'documentclass': '[journal]IEEEtran', 'preamble': [r'\usepackage{times}']})`.
- [x] The font size for figure captions is incorrectly detected, I believe.  This may be just because I have tweaked the style file a little bit, but I think that all figure captions in IEEEtran use `\footnotesize`, not `\small`.  You have `\small` hardcoded rather than detected for most figure font sizes, so I believe this is the discrepancy.  
- [x] Related: it is unnecessarily difficult to adjust figure font sizes.  I would recommend detecting if a user has passed e.g. `pubplot.Document({...}, style={'font.size': '8'}`, and override all font settings with the specified `font.size` key.  If the user of your library is wanting to override this value, they probably want it to be the default for everything, and could then manually specify `xtick.labelsize` for instance.  **Adding this would make the previous issue less of a bother.**
- [x] Need a `Document.figure()` method which takes a GridSpec for the axes rather than always using subplots ([GridSpec](https://matplotlib.org/users/gridspec.html; or perhaps better, [using fig.add_gridspec and fig.add_subplot](https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_gridspec)).  What I would recommend is having `Document.figure()` return a figure object without creating any axes, and then hook into `Figure.add_gridspec` and `Figure.add_subplot` like the second link.
- [x] The implementation of `tight_layout` is wrong, leading to font sizes not matching the document.  Currently, `pubplot` does `Figure(..., tight_layout=True)` in `document.py` and later `canvas.print_figure(..., bbox_inches='tight')` in `figure.py`.  To get the spacing / sizing right, these need to be `Figure(..., tight_layout={'pad': 0})` and `canvas.print_figure(..., bbox_inches='tight', pad_inches=0)` respectively.

Since you've already put a bit of time into this project, I'll go ahead and make a pull request with everything except the figure caption size detection for IEEEtran.  We can have a dialog there.

**Comment by hsadok** [comment]
This idea of using the font size from the captions as default is really cool. When I started to implement pubplot this was what I had in mind. However, I still could not figure out how to do it...

**Comment by wwoods** [comment]
Right - I think the way to do it would be to put a figure with a caption in the demo page, and [print the current font size](https://tex.stackexchange.com/a/24600/73154).

**Comment by hsadok** [comment]
@wwoods I managed to implement it! (see ba529cfa35afa5876e1d2ab692cc2a5cced35133)

Previously, my solution to retrieve sizes from the LaTeX document was to store them in LaTeX lengths and then save all these lengths to an auxiliary file. However, I simply could not store the font size when inside a figure caption. So instead, I decided to write all these sizes right to the LaTeX compilation log and use a pattern to be able to detect them. Long story short, now `pubplot` can detect caption sizes and defaults all sizes to the caption size.

**Comment by wwoods** [comment]
Ah, nifty!  Good work :)

**Comment by wwoods** [comment]
PS - any idea when you plan on merging dev -> master and pushing a new release?  One of my undergraduates is looking into using this package, and I suspect it would be good to have him working off of the caption sizing / other fixes we've applied in your original repository rather than my fork.

**Comment by hsadok** [comment]
I looked at the issue with Python 2.7 and I am almost convinced it is a bug in matplotlib. Since we are likely the only two using this library at the moment, and you seem to be using Python3, I will merge this right away. I plan to later try to isolate the bug and submit an issue to matplotlib. Hopefully, if they still care about python2, they will fix it.

**Comment by hsadok** [comment]
@wwoods I noticed travis was having trouble to deploy to PyPI but I think I have finally fixed it. You or you undergraduate can now use pip install to use pubplot :-)

**Comment by wwoods** [comment]
Ha, thanks!  Very good.  Still using pubplot proudly :+1:
